### PR TITLE
Distance to differentiate touch from mouse

### PR DESCRIPTION
**Pull request by sreyemnayr**
So I got this far... An attribute on the `MouseListener.event_data` dict called "distance" only gets added to if the mouse isn't being pressed. 
Because essentially, on a touch screen if you're moving, you're dragging.
So now I'm stuck because I'm having trouble sorting out what happens to that event_data when the polling happens. Right now, obviously, it's a bool of afk or not-afk. What I'm trying to sort out is how to change "not-afk" to be "not-afk-touch" or "not-afk-mouse" depending on that "distance" reading. Does that make sense?

### CODE REVIEW

**Comment by johan-bjareholt** [comment]
>  Because essentially, on a touch screen if you're moving, you're dragging.

True, but that means that the watcher should only react to button releases as that's the only time that it can know if the mouse was dragged or not.

But another thing is that this assumption is not really correct because even though you mostly don't drag with a mouse, sometimes you do and that would create incorrect data because of that assumption.

Without that in mind, I pulled down these changes and they seem to work on my linux laptop with a touch screen.

**Comment by sreyemnayr** [comment]
I think that would be okay. It would be really unlikely to not move your mouse at all before or after dragging.
I think if only when “distance” is zero it assumes touch, it would be pretty close to accurate...
It’s not exclusively reacting to button releases. It’s setting an “is the button down” flag on press and unsetting it on release from the click event (which fires on both down and up) and then either does or does not calculate “distance” depending on if that flag is set.
Were you able to make it report a different status based on the distance being equal to zero?
Or maybe I should just strip everything but the touch detection out and make it it’s own independent watcher? Can you have more than one mouse event listener going at once?

Ryan

________________________________

**Comment by johan-bjareholt** [comment]
> I think if only when “distance” is zero it assumes touch, it would be pretty close to accurate...

I'm not sure if I understood things correctly then, as you often would for example scroll on web pages on a touch screen which would mean that you are emitting a "button down" on one place and a "button up" at a distance quite far away which means that the distance is quite long. I was unable to ever make the distance less than 0 when using the touch screen except for the first event where self.pos was not set. Maybe the behavior is just different on Linux though, don't know.

> Were you able to make it report a different status based on the distance being equal to zero?

On my laptop it was easy as the mouse button is easily clickable without moving the touch pad.

> Or maybe I should just strip everything but the touch detection out and make it it’s own independent watcher? Can you have more than one mouse event listener going at once?

That's probably also a good idea, but it's fine to prototype like this until you know what works and what does not. There should be no issue with having more than one mouse event listener.

**Comment by sreyemnayr** [comment]
Right, it only adds distance when the mouse button is not down, so only the mouse should add to the distance attribute (and only when it’s not dragging). The touch would increment the “clicks” and delta, but only mouse-not-dragging would increment distance.
It would false-positive for touch if you were dragging the entire length of the polling interval, but that seems pretty unlikely.
It’s just that I don’t know where I could conditionally check for that event_data.distance information when reporting the event.

Ryan

________________________________

**Comment by sreyemnayr** [comment]
And yes, if you clicked the mouse button without moving it at all, it would also false-positive for touch... but that seems pretty unlikely as well. Even if you did it on accident, it’s likely that you’d have to move the cursor to correct whatever you’d just done...

Ryan

________________________________

**Comment by johan-bjareholt** [comment]
I'm closing this PR.
It's cool and all, but most users are not on touch screens and even if they were we have no use-case for the distance property yet so it would only take up database space.
Even if we had a use-case for it we would have to debate whether it should fit into this watcher or into a separate one.

**Pull request closed without merging**
