### PR TITLE
Made AFK timestamps and durations correct

### PR DESCRIPTION
**Pull request by johan-bjareholt**

### CODE REVIEW

**Comment by ErikBjare** [comment]
This will probably solve a few bugs I've been having, merging!

**Comment by johan-bjareholt** [comment]
I still seem to have some issues though, the best working commit is still in my opinion c1f6d73425fe7f6cf8fdf9002ac6

**Comment by ErikBjare** [comment]
@johan-bjareholt What kind of issues? [A lot that has happened since that commit](https://github.com/ActivityWatch/aw-watcher-afk/compare/c1f6d73425fe7f6cf8fdf9002ac6928a25f6165c...master).

**Comment by johan-bjareholt** [comment]
Too long AFK events and sometimes events do not merge are the ones I am aware of.

**Pull request merged**
